blueprint_chat.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db
from datetime import datetime

bp_chat = Blueprint("bp_chat",__name__)

@bp_chat.route('/private',methods=["POST","GET"])
def content_private_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    if session['role'] == 'user':
        query = '''

            select * 
            from hub
            where pasId like '%s'

        '''%(session['userId'])
    
    else:
        user = request.args.get("userId")
        query = '''

            select * 
            from hub
            where pasId like '%s'

        '''%(user)

    df = db.df_query(query)
    
    if len(df) !=0:
        if df.iloc[0]['flag'] == 1:
            if session['role'] == 'user':
                query = """
                    select *
                    from pesan
                    where pengirimId like '%s' or penerimaId like '%s'
                """%(session['userId'],session['userId'])
            else:
                user = request.args.get("userId")
                query = """
                    select *
                    from pesan
                    where pengirimId like '%s' or penerimaId like '%s'
                """%(user,user)

            df = db.df_query(query)
            if len(df)!=0:
                array_chat = df.values.tolist()
                if session['role'] == 'user':
                    return render_template('content_private_chat.html',array_chat=array_chat)
                else:
                    return render_template('content_private_chat.html',array_chat=array_chat,user=user)
            else:
                if session['role'] == 'user':
                    return render_template('content_private_chat.html')
                else:
                    return render_template('content_private_chat.html',user=user)
        
        else:
            if session['role'] == 'user':
                return redirect('/home')
            else:
                return redirect('/list_chat')


    else:
        query = """
        SELECT userId FROM users
        where role like 'dokter'
        ORDER BY RANDOM() LIMIT 1
        """
        dokter = db.execute_query_one(query)
        query ="""
        insert into hub values('%s','%s','1')
        """%(dokter,session['userId'])

        db.execute_query(query)
        if session['role'] == 'user':
            return render_template('content_private_chat.html')
        else:
            return render_template('content_private_chat.html',user=user)



    # df = db.df_query(query)

    # if len(df) == 0:
    #     query = """
    #     SELECT userId FROM users
    #     where role like 'dokter'
    #     ORDER BY RANDOM() LIMIT 1
    #     """
    #     dokter = db.execute_query_one(query)
    #     query ="""
    #     insert into hub values('%s','%s')
    #     """%(dokter,session['userId'])
    #     # db.execute_query(query)
    #     if session['role'] == 'user':
    #         return render_template('content_private_chat.html')
    #     else:
    #         return render_template('content_private_chat.html',user=user)
    # else :
    #     array_chat = df.values.tolist()
    #     if session['role'] == 'user':
    #         return render_template('content_private_chat.html',array_chat=array_chat)
    #     else:
    #         return render_template('content_private_chat.html',array_chat=array_chat,user=user)

    return 'oke'


@bp_chat.route('/send',methods=["POST","GET"])
def content_send_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    if session['role'] == 'user':
        query ="""
        select count(*)
        from pesan
        """
        jml = db.execute_query_one(query)
        jml = jml+1
        query = """
        select dokId
        from hub
        where pasId like '%s'
        """%(session['userId'])
        dokter = db.execute_query_one(query)
        isi = request.form.get("chat")
        tl = datetime.today().strftime('%Y-%m-%d')
        hl = datetime.today().strftime('%H:%M')
        query = """
        insert into pesan values('%s','%s','%s','%s','%s','%s','')
        """%(jml,session['userId'],dokter,isi,tl,hl)
        db.execute_query(query)

        return redirect('/private')

    else:
        query ="""
        select count(*)
        from pesan
        """
        jml = db.execute_query_one(query)
        jml = jml+1
        user = request.args.get('user')
        isi = request.form.get("chat")
        tl = datetime.today().strftime('%Y-%m-%d')
        hl = datetime.today().strftime('%H:%M')
        query = """
        insert into pesan values('%s','%s','%s','%s','%s','%s','')        
        """%(jml,session['userId'],user,isi,tl,hl)
        db.execute_query(query)

        return redirect('/private?userId='+user)

@bp_chat.route('/list_chat',methods=["POST","GET"])
def content_list_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = """
    select distinct(pasId)
    from hub
    where dokId like '%s'
    """%(session['userId'])
    df = db.df_query(query)
    if len(df) == 0:
        return render_template('content_dokter_user_chat.html')
    else:
        users=[]
        list_user = df.values.tolist()
        a = 0
        for i in list_user:
            query="""
            select *
            from users
            where userId like '%s'
            """%(i[0])
            df = db.df_query(query)
            if len(df)>0:
                df = df.iloc[0]
                df = df.values.tolist()
                users.append(df)
        
        return render_template('content_dokter_user_chat.html',pasien=users)


@bp_chat.route('/end_chat',methods=["POST","GET"])
def end_chat():

    if session['role'] == 'user':

        query = """
            UPDATE hub
            SET flag=0
            WHERE pasId like '%s'
            """%(session['userId'])

        db.execute_query(query)

        return redirect('/home')
    
    else:

        return redirect('/list_chat')

@bp_chat.route('/add_summary',methods=["POST","GET"])
def add_summary():
    user = request.args.get("user")
    note = request.form.get("notes")

    query = '''
    select count(*)
    from dokter_summary
    '''
    tl = datetime.today().strftime('%Y%m%d')
    hasil = db.execute_query_one(query)
    hasil = hasil+1
    smid = 'sm'+str(tl)+str(hasil)
    tl = datetime.today().strftime('%Y-%m-%d')

    query = """
    
    insert into dokter_summary values ('%s','%s','%s','%s','%s')
    
    """%(smid,tl,session['userId'],user,note)

   
    db.execute_query(query)
    query = """
            UPDATE hub
            SET flag=0
            WHERE pasId like '%s'
            """%(user)

    db.execute_query(query)

    

    return redirect('/end_chat')

blueprint_profile.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db
import pandas as pd
from flask_paginate import Pagination, get_page_parameter

PER_PAGES = 5
bp_profile = Blueprint("bp_profile",__name__)

@bp_profile.route("/user-profile",methods=["POST","GET"])
def user_profile():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    userId = session['userId']
    query = '''
    
    select *
    from users
    where userId like '%s'
    
    '''%(str(userId))
    user = db.df_query(query)
    parsed = user.to_json(orient="records")
    user_json = json.loads(parsed)
    
    return render_template('content_user_profile.html',user = user_json[0])

@bp_profile.route('/update-users', methods=['POST',"GET"])
def update_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    hasil = request.form.to_dict(flat=False)
    
    string = ""
    for i in hasil.items():
        if len(i[1][0]) > 0 :
            qry = str(i[0])+" = '%s',"%(i[1][0])
            string = string+qry

    userId = session['userId']
    query = """
    UPDATE users
    SET %s
    WHERE userId = '%s'
    """%(string[:-1],userId)
    db.execute_query(query)
    return redirect("/user-profile")


@bp_profile.route('/list_user', methods=['POST',"GET"])
def list_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = '''
    select *
    from users
    where role like 'user'
    '''
    all_user = db.df_query(query)
    list_user = all_user.values.tolist()
    return render_template('content_admin_list_user.html',list_user=list_user)


@bp_profile.route('/delete_list_user', methods=['POST',"GET"])
def delete_list_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    userId = request.args.get("userId")
    query = """
    delete from users
    where userId like '%s'
    """%(userId)
    db.execute_query(query)

    return redirect("/list_user")

#################################################################################penyakit

@bp_profile.route('/list_penyakit', methods=['POST',"GET"])
def list_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    search = False
    q = request.args.get('q')
    if q:
        search = True

    page = request.args.get(get_page_parameter(), type=int, default=1)

    query = '''
    select *
    from penyakit
    '''
    all_penyakit = db.df_query(query)
    list_penyakit = all_penyakit.values.tolist()

    i=(page-1)*PER_PAGES
    penyakit_page = list_penyakit[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_penyakit), search=search, record_name='List')

    return render_template('content_admin_list_penyakit.html',penyakit = penyakit_page, pagination=pagination,css_framework='bootstrap4')

@bp_profile.route('/delete_penyakit', methods=['POST',"GET"])
def delete_penyakit():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    penyakitId = request.args.get("penyakitId")
    query = """
    delete from penyakit
    where penyakitId like '%s'
    """%(penyakitId)
    db.execute_query(query)
    query = """
    delete from relasi 
    where penyakitId like '%s'
    """%(penyakitId)
    db.execute_query(query)

    return redirect("/list_penyakit")

@bp_profile.route('/page_add_penyakit', methods=['POST',"GET"])
def page_add_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = '''
    select *
    from gejala
    '''
    all_gejala = db.df_query(query)
    list_gejala = all_gejala.values.tolist()

    return render_template('content_admin_add_penyakit.html',gejala=list_gejala)

@bp_profile.route('/add_penyakit', methods=['POST',"GET"])
def add_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    data = request.form.getlist('gejalabox')
    name = request.form.get("name")
    keterangan = request.form.get("keterangan")
    level = request.form.get("level")
    query="""
    select count(*)
    from penyakit
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'R'+str(id)
    query="""
    insert into penyakit values('%s','%s','%s','%s','')
    """%(id,name,keterangan,level)
    db.execute_query(query)
    for i in data:
        query = """
        insert into relasi values ('%s','%s')
        """%(id,i)
        db.execute_query(query)

    return redirect('/list_penyakit')


#################################################################################gejala

@bp_profile.route('/list_gejala', methods=['POST',"GET"])
def list_gejala():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    page = request.args.get(get_page_parameter(), type=int, default=1)
    query = '''
    select *
    from gejala
    '''
    all_gejala = db.df_query(query)
    list_gejala = all_gejala.values.tolist()
    i=(page-1)*PER_PAGES
    gejala_page = list_gejala[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_gejala), record_name='List')

    return render_template('content_admin_list_gejala.html',gejala = gejala_page,pagination = pagination)

@bp_profile.route('/delete_gejala', methods=['POST',"GET"])
def delete_gejala():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    gejalaId = request.args.get("gejalaId")
    query = """
    delete from gejala
    where gejalaId like '%s'
    """%(gejalaId)
    db.execute_query(query)
    query = """
    delete from relasi
    where gejalaId like '%s'
    """%(gejalaId)
    db.execute_query(query)
    return redirect("/list_gejala")

@bp_profile.route('/page_add_gejala', methods=['POST',"GET"])
def page_add_gejala():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    return render_template('content_admin_add_gejala.html')


@bp_profile.route('/add_gejala', methods=['POST',"GET"])
def add_gejala():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    name = request.form.get("name")
    pertanyaan = request.form.get("pertanyaan")
    query="""
    select count(*)
    from gejala
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'G'+str(id)
    query="""
    insert into gejala values ('%s','%s','%s')
    """%(str(id),str(name),str(pertanyaan))
    db.execute_query(query)

    return redirect('/list_gejala')

#######################################################drug

@bp_profile.route('/list_drug', methods=['POST',"GET"])
def list_drug():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    page = request.args.get(get_page_parameter(), type=int, default=1)
    query = '''
    select *
    from obat
    '''
    all_obat = db.df_query(query)
    list_obat = all_obat.values.tolist()
    i=(page-1)*PER_PAGES
    obat_page = list_obat[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_obat), record_name='List')

    return render_template('content_admin_list_drug.html',obat = obat_page,pagination = pagination)
 
@bp_profile.route('/delete_obat', methods=['POST',"GET"])
def delete_obat():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    obatId = request.args.get("obatId")
    query = """
    delete from obat
    where obatId like '%s'
    """%(obatId)
    db.execute_query(query)

    return redirect('/list_drug')

@bp_profile.route('/page_add_obat', methods=['POST',"GET"])
def page_add_obat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query="""
    
    select penyakitId,name
    from penyakit
    
    
    """
    df = db.df_query(query)
    df = df.values.tolist()

    return render_template('content_admin_add_obat.html',penyakit=df)

@bp_profile.route('/add_obat', methods=['POST',"GET"])
def add_obat():

    name = request.form.get("name")
    pertanyaan = request.form.get("pertanyaan")
    penyakit = request.form.get("penyakit")

    query="""
    select count(*)
    from obat
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'B'+str(id)
    
    query ="""
    insert into obat values ("%s","%s","%s","%s")
    """%(id,penyakit,name,pertanyaan)

    db.execute_query(query)

    return redirect('/list_drug')

# for i in hasil.items():
#     if len(i[1][0]) > 0 :
#         if i[1][0].isnumeric():
#             qry = str(i[0])+" = %s,"%(i[1][0])
#         else:
#             qry = str(i[0])+" = '%s',"%(i[1][0])
#         print(qry)
#         string = string+qry

blueprint_register.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request,flash
import requests
import json
import database as db
from datetime import datetime
from uuid import uuid4

bp_register = Blueprint('bp_register', __name__)

@bp_register.route('/register')
def register():
    return render_template('register.html')

@bp_register.route('/register-users', methods=['POST'])
def register_user():

    email = request.form.get("email")
    name = request.form.get("name")
    psw = request.form.get("psw")
    psw2 = request.form.get("psw-repeat")

    if '@' not in email and len(email) <5:

        flash('please use "@" on email address form')
        return redirect("/register")
    if len(psw) < 8 :
        flash('password must at least 8')
        return redirect("/register")
    if psw != psw2:
        flash('unmatch password on repeat password')
        return redirect("/register")

    query = '''
    select count(*)
    from users
    '''

    #createuserID
    tl = datetime.today().strftime('%Y%m%d')
    hasil = db.execute_query_one(query)
    hasil = hasil+1
    userid = 'usr'+str(tl)+str(hasil)
    role = 'user'
    socket = uuid4().hex

    insert = """
    insert into users values('%s','%s','%s','%s','%s','','','','','','%s')
    """%(str(userid),str(name),str(psw),str(role),str(email),str(socket))
    db.execute_query(insert)

    insert = """
    insert into wallet values('%s',0)
    """%(str(userid))
    db.execute_query(insert)

    return redirect("/")

templates/content_admin_homepage.html
{% extends 'template_base.html' %}
{% block title %}Admin - Pardoc{% endblock %} 
{% block content %} 


{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="testimonials">
<div class="row">
	<div class="large-12 large-centered column">
	<h3>ERROR</h3>
	<span>
	{% for message in messages %}
	{{ message }}
	{% endfor %}
	</span><p></p>
</div>
</div>
</section>
{% endif %}
{% endwith %}

<article>
<div class="container masthead">
	<h1 class="text-center mb-5">Dashboard</h1>
	<div class="row justify-content-center">

		
		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_users')}}" style="text-decoration: none;">
				<div class="card border-left-primary shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total User</div>
								<div class="h5 mb-0 font-weight-bold ">2</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-users fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_penyakit')}}" style="text-decoration: none;">
				<div class="card border-left-danger shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Diasease</div>
								<div class="h5 mb-0 font-weight-bold ">9</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-square-virus fa-2x "></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="row justify-content-center">

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_gejala')}}" style="text-decoration: none;">
				<div class="card border-left-warning shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Symptoms</div>
								<div class="h5 mb-0 font-weight-bold ">28</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-file-waveform fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_drug')}}" style="text-decoration: none;">
				<div class="card border-left-success shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Drug</div>
								<div class="h5 mb-0 font-weight-bold ">3</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-capsules fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>
</div>
</article>

{% endblock %}

templates/content_admin_list_penyakit.html
{% extends 'template_base.html' %} 
{% block title %}List Disease{% endblock %} 
{% block content %}

<div id="view"> 
  <div class="container masthead">
    <!-- Page Heading -->
    <h1 class="h3 mb-5 text-gray-800">Tables</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Diasease</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th>NO</th>
                        <th>NAME DIASEASE</th>
                        <th>LEVEL</th>
                        <th>ACTION</th>
                      </tr>
                    </thead>
                    <!-- <tfoot>
                      <tr>
                        <th>NO</th>
                        <th>NAMA USER</th>
                        <th>LEVEL</th>
                        <th>ACTION</th>
                      </tr>
                    </tfoot> -->
                    <tbody>
                      {% for i in penyakit %}
                        <tr>
                          <td>{{ loop.index + pagination.skip }}</td>
                          <td>{{ i[1] }}</td>
                          <td>{{ i[3] }}</td>
                          <td><a href="{{ url_for('bp_profile.delete_penyakit',penyakitId = i[0]) }}" class="btn btn-danger">
                            <i class="fa-solid fa-trash"></i>
                            DELETE</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="text-center mt-4 mb-2">
          {{ pagination.info }}
        </div>
        <div class="wrappagination mb-4">
          {{ pagination.links }} 
        </div>
        {% if session['role'] == 'dokter' %}
        <a href="{{ url_for('bp_profile.page_add_penyakit') }}" class="btn btn-primary m-4">ADD DISEASE</a>
        {% endif %}
    </div>
  </div>
</div> 
<!-- <div id="view"> 
  <div class="container">
    <div class="row justify-content-center">
      <table class="tableDisease mt-4">
        <thead>
          <tr>
            <th>NO</th>
            <th>NAME DISEASE</th>
            <th>LEVEL</th>
            <th>ACTION</th>
          </tr>
        </thead>
        <tbody>
          {% for i in penyakit %}
            <tr>
              <td>{{ loop.index + pagination.skip }}</td>
              <td>{{ i[1] }}</td>
              <td>{{ i[3] }}</td>
              <td><a href="{{ url_for('bp_profile.delete_penyakit',penyakitId = i[0]) }}" class="btn btn-danger">DELETE</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
      <div class="text-center mt-4 mb-2">
        {{ pagination.info }}
      </div>
      <div class="wrappagination mb-4">
        {{ pagination.links }} 
      </div>
      {% if session['role'] == 'dokter' %}
      <a href="{{ url_for('bp_profile.page_add_penyakit') }}" class="btn btn-dark">Add DISEASE</a>
      {% endif %}
    </div>
    
  </div>
</div>    -->


{% endblock %}

templates/content_dokter_homepage.html
{% extends 'template_base.html' %} 
{% block title %}Doktor - Pardoc{% endblock %} 
{% block content %}


{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="testimonials">
<div class="row">
	<div class="large-12 large-centered column">
	<h3>ERROR</h3>
	<span>
	{% for message in messages %}
	{{ message }}
	{% endfor %}
	</span><p></p>
</div>
</div>
</section>
{% endif %}
{% endwith %}

<article>

<div class="container masthead">
	<h1 class="text-center mb-5">Dashboard</h1>
	<div class="row justify-content-center">

		
		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_chat.content_list_chat')}}" style="text-decoration: none;">
				<div class="card border-left-primary shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Chat</div>
								<div class="h5 mb-0 font-weight-bold ">2</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-comments fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_penyakit')}}" style="text-decoration: none;">
				<div class="card border-left-danger shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Diasease</div>
								<div class="h5 mb-0 font-weight-bold ">9</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-square-virus fa-2x "></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="row justify-content-center">

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_gejala')}}" style="text-decoration: none;">
				<div class="card border-left-warning shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Symptoms</div>
								<div class="h5 mb-0 font-weight-bold ">28</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-file-waveform fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>

		<div class="col-xl-4 col-md-6 mb-4">
			<a href="{{ url_for('bp_profile.list_drug')}}" style="text-decoration: none;">
				<div class="card border-left-success shadow h-100 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									Total Drug</div>
								<div class="h5 mb-0 font-weight-bold ">3</div>
							</div>
							<div class="col-auto">
								<i class="fa-solid fa-capsules fa-2x"></i>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>
</div>
	
</article>
<!-- <div class="container">
	<div class="btnListUser col-12">
		<a href="{{ url_for('bp_chat.content_list_chat')}}">CHAT PATIENT</a>
	</div>
	
	<div class="row justify-content-center">
		<div class="col-4">
			<div class="btnListDisease w-100">
				<a href="{{ url_for('bp_profile.list_penyakit')}}">LIST DISEASE</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListSymtoms w-100">
				<a href="{{ url_for('bp_profile.list_gejala')}}">LIST SYMPTOMS</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListDrug w-100">
				<a href="{{ url_for('bp_profile.list_drug')}}">LIST DRUG</a>
			</div>
		</div>
	</div>

</div> -->



{% endblock %}

templates/topup.html
<div class="modal-lg fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Understood</button>
        </div>
      </div>
    </div>
  </div>